"""add asset quantity, status updates, production avg egg weight, transaction unit price

Revision ID: 47a396393e74
Revises: 0001
Create Date: 2026-08-30 08:02:46.184770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_status_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    op.add_column('daily_transactions', sa.Column('unit_price', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('average_egg_weight_kg', sa.Float(), server_default='0.055', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'average_egg_weight_kg')
    op.drop_column('daily_transactions', 'unit_price')
    op.drop_column('assets', 'quantity')
    op.drop_table('asset_status_updates')
    # ### end Alembic commands ###
